spring.application.name=gestion-laboratorio
server.port = 8082
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_laboratorios
spring.datasource.username=root
spring.datasource.password=Roblor84+

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true